CREATE DATABASE IF NOT EXISTS imec_site CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE imec_site;

CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(160) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('admin') NOT NULL DEFAULT 'admin',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE company_settings (id INT PRIMARY KEY DEFAULT 1,company_name VARCHAR(160) NOT NULL DEFAULT 'IMEC Metalúrgica',logo_url VARCHAR(255),phone VARCHAR(60),whatsapp VARCHAR(60),email VARCHAR(160),address VARCHAR(255),city VARCHAR(120),state VARCHAR(80),hero_image_url VARCHAR(255),youtube_url VARCHAR(255),instagram_url VARCHAR(255),linkedin_url VARCHAR(255),facebook_url VARCHAR(255),updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE pages (id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(80) NOT NULL UNIQUE,title VARCHAR(180) NOT NULL,subtitle TEXT,content LONGTEXT,image_url VARCHAR(255),is_active TINYINT(1) NOT NULL DEFAULT 1,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE services (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(160) NOT NULL,slug VARCHAR(180) NOT NULL UNIQUE,short_description TEXT,description LONGTEXT,icon VARCHAR(80),image_url VARCHAR(255),display_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE portfolio_projects (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,slug VARCHAR(200) NOT NULL UNIQUE,category VARCHAR(120),location VARCHAR(160),year VARCHAR(20),short_description TEXT,description LONGTEXT,cover_image_url VARCHAR(255),display_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE gallery_categories (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(140) NOT NULL,slug VARCHAR(160) NOT NULL UNIQUE,display_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1);
CREATE TABLE gallery_photos (id INT AUTO_INCREMENT PRIMARY KEY,category_id INT,title VARCHAR(180) NOT NULL,image_url VARCHAR(255) NOT NULL,alt_text VARCHAR(220),display_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (category_id) REFERENCES gallery_categories(id) ON DELETE SET NULL);
CREATE TABLE videos (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,youtube_url VARCHAR(255) NOT NULL,description TEXT,display_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE quote_requests (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,company VARCHAR(160),email VARCHAR(160) NOT NULL,phone VARCHAR(80) NOT NULL,service_interest VARCHAR(160),message TEXT NOT NULL,status ENUM('novo','em_contato','finalizado') NOT NULL DEFAULT 'novo',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

INSERT INTO company_settings (id,company_name,phone,whatsapp,email,address,city,state,hero_image_url) VALUES (1,'IMEC Metalúrgica','(47) 99942-3000','5547999423000','contato@imecmetalurgica.com.br','Joinville - SC, Brasil','Joinville','Santa Catarina','') ON DUPLICATE KEY UPDATE company_name=VALUES(company_name);
INSERT INTO pages (slug,title,subtitle,content) VALUES ('home','Soluções Industriais com Engenharia, Tecnologia e Confiança','Excelência em caldeiraria, soldagem, manutenção industrial, estruturas metálicas, NR-13, rigging e responsabilidade técnica.','A IMEC Metalúrgica atua com soluções industriais completas para empresas que exigem segurança, qualidade e responsabilidade técnica.'),('quem-somos','Engenharia industrial com responsabilidade técnica','Atuação profissional para projetos, fabricação, montagem e manutenção industrial.','A IMEC Metalúrgica entrega soluções sob medida para a indústria, unindo experiência técnica, processos seguros e compromisso com desempenho.'),('orcamento','Solicite um orçamento','Conte sobre sua demanda industrial.','Atendemos demandas de caldeiraria, soldagem, estruturas metálicas, montagem, tubulações, manutenção, NR-13 e rigging.') ON DUPLICATE KEY UPDATE title=VALUES(title);
INSERT INTO services (title,slug,short_description,description,icon,display_order) VALUES ('Caldeiraria Industrial','caldeiraria-industrial','Fabricação e montagem de equipamentos, peças e conjuntos metálicos.','Soluções em caldeiraria para fabricação, adequação e montagem industrial.','Factory',1),('Soldagem Industrial','soldagem-industrial','Processos de soldagem para aplicações industriais.','Soldagem industrial com atenção à qualidade e conformidade técnica.','Wrench',2),('Manutenção Industrial','manutencao-industrial','Manutenção preventiva, corretiva e apoio técnico.','Serviços com foco em segurança operacional e disponibilidade.','Settings',3),('Estruturas Metálicas','estruturas-metalicas','Projeto, fabricação e montagem sob medida.','Estruturas metálicas para obras industriais.','Building2',4),('NR-13','nr-13','Adequação, inspeções, laudos e documentação.','Apoio técnico para conformidade com NR-13.','Gauge',5),('Rigging e Movimentação de Cargas','rigging-movimentacao-cargas','Planejamento e execução de içamento.','Operações de rigging com foco em segurança.','Crane',6),('Montagem Industrial','montagem-industrial','Montagem de equipamentos, linhas e conjuntos.','Execução de montagem industrial com planejamento de campo.','HardHat',7),('Tubulações Industriais','tubulacoes-industriais','Fabricação e montagem de tubulações.','Tubulações industriais para processos e utilidades.','Pipelines',8) ON DUPLICATE KEY UPDATE title=VALUES(title);
INSERT INTO gallery_categories (name,slug,display_order) VALUES ('Caldeiraria','caldeiraria',1),('Soldagem','soldagem',2),('Estruturas Metálicas','estruturas-metalicas',3),('Montagem Industrial','montagem-industrial',4) ON DUPLICATE KEY UPDATE name=VALUES(name);
